# NyaaStats configuration
web:
  title: Nyaa Stats # website title
  servername: Minecraft Server # Server Name
  homepage: https://minecraft.example.com # Your homepage

render:
  level: data/level.dat # file path here, required
  playerdata: data/playerdata # directory path here, required
  stats: data/stats # directory path here, required
  advancements: data/advancements # advancements path here, required
  whitelist: whitelist.json # file path here, leave blank to disable
  banned-players: banned-players.json # file path here, leave blank to disable
  render-banned: false  # do not render banned players
  output: web/static/data # directory path here, required
  time-format: # time format on display, details http://momentjs.com/docs/#/displaying/format/
    full: dddd, MMMM Do, YYYY HH:mm:ss ZZ
    short: MMMM Do, YYYY
    compact: YYYY-M-D HH:mm:ss

api:
  ratelimit: 2 # set to 1 request per sec as per mojang api rate limit
  max-name-history: 3 # Maximum history will be recorded

# Set advancements progresses
# Details: http://minecraft.gamepedia.com/Advancements
advancements-progress:
  nether:
    all_potions: 11
    all_effects: 20
  adventure:
    kill_all_mobs: 22
    adventuring_time: 36
  husbandry:
    bred_all_animals: 10
    balanced_diet: 35
